-- AlterTable
ALTER TABLE "Autor" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Kategorija" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Knjiga" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "KorisnikKnjiga" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
